Reemplaza su contenido por:

name: CI

on:

pull_request:

branches: [ main, develop ]

push:

branches: [ develop ]

permissions:

contents: read

jobs:

lint-test:

runs-on: ubuntu-latest

steps:

- uses: actions/checkout@v4
- uses: actions/setup-python@v5
    
    with:
    
    python-version: "3.11"
    
- run: pip install -U pip ruff pytest
- name: Lint (no-break)
    
    run: ruff check . || true
    
- name: Tests (no-break)
    
    run: pytest -q || true
