name: Trivy Image Scan

on:

workflow_run:

workflows: [ "Docker Publish" ]

types: [ completed ]

permissions:

security-events: write

actions: read

contents: read

jobs:

trivy:

if: $ github.event.workflow_run.conclusion == 'success'

runs-on: ubuntu-latest

steps:

- uses: aquasecurity/trivy-action@0.24.0
    
    with:
    
    image-ref: [ghcr.io/mimave/train-tcs:latest](http://ghcr.io/mimave/train-tcs:latest)
    
    format: sarif
    
    output: trivy.sarif
    
    severity: CRITICAL,HIGH
    
- uses: github/codeql-action/upload-sarif@v3
    
    with:
    
    sarif_file: trivy.sarif
